name: Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'

jobs:
  continuous-integration: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: npm install
      #Test
      - run: npm run test:unit
    
  continuous-delivery:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy to heroku development enviroment
        uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
        with:
          api_key: "53083cb5-e9d1-400f-9741-54fc664d0784"
          email: "tropsmart18@gmail.com"
          app_name: "ts-appsweb-dev"
          branch: "master"

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy to heroku production enviroment
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: "26e9942e-8c58-4c0f-a37c-c10936bf7835"
          heroku_app_name: "ts-appsweb-fe"
          heroku_email: "digihazard18@gmail.com"